src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Entity\Enum\Status;
use App\Repository\EntrepriseRepository;
use App\Validator as AppAssert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
#[AppAssert\EmailEntrepriseUnique]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::GUID)]
    private ?string $uuid = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 255, maxMessage: 'Le nom de l\'entreprise ne doit pas dépasser {{ limit }} caractères')]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 50, maxMessage: 'Le numéro de SIRET ne doit pas dépasser {{ limit }} caractères')]
    private ?string $numeroSiret = null;

    #[ORM\Column(length: 20)]
    #[Assert\Regex(
        pattern: '/^(?:0|\(?\+33\)?\s?|0033\s?)[1-9](?:[\.\-\s]?\d\d){4}$/',
        match: true,
        message: 'Merci de saisir le numéro de téléphone au bon format'
    )]
    private ?string $telephone = null;

    #[ORM\Column(length: 100, nullable: true)]
    #[Assert\Length(max: 100, maxMessage: 'Le numéro de label ne doit pas dépasser {{ limit }} caractères')]
    private ?string $numeroLabel = null;

    #[Assert\NotBlank]
    #[Assert\Email]
    #[Assert\Length(max: 255, maxMessage: 'L\'adresse e-mail ne doit pas dépasser {{ limit }} caractères')]
    private ?string $email = null;

    #[ORM\ManyToMany(targetEntity: Territoire::class, inversedBy: 'entreprises')]
    private Collection $territoires;

    #[ORM\OneToMany(mappedBy: 'entreprise', targetEntity: Signalement::class)]
    private Collection $signalements;

    #[ORM\OneToMany(mappedBy: 'entreprise', targetEntity: Employe::class)]
    private Collection $employes;

    #[ORM\OneToOne(targetEntity: User::class, mappedBy: 'entreprise')]
    private $user;

    #[ORM\OneToMany(mappedBy: 'entreprise', targetEntity: Intervention::class)]
    private Collection $interventions;

    #[ORM\OneToMany(mappedBy: 'entreprise', targetEntity: MessageThread::class)]
    private Collection $messagesThread;

    public function __construct()
    {
        $this->territoires = new ArrayCollection();
        $this->signalements = new ArrayCollection();
        $this->employes = new ArrayCollection();
        $this->interventions = new ArrayCollection();
        $this->messagesThread = new ArrayCollection();
        $this->uuid = uniqid();
    }

    public function __toString(): string
    {
        return $this->nom;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNumeroSiret(): ?string
    {
        return $this->numeroSiret;
    }

    public function setNumeroSiret(string $numeroSiret): self
    {
        $this->numeroSiret = $numeroSiret;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getNumeroLabel(): ?string
    {
        return $this->numeroLabel;
    }

    public function setNumeroLabel(?string $numeroLabel): self
    {
        $this->numeroLabel = $numeroLabel;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection<int, Territoire>
     */
    public function getTerritoires(): Collection
    {
        return $this->territoires;
    }

    public function addTerritoire(Territoire $territoire): self
    {
        if (!$this->territoires->contains($territoire)) {
            $this->territoires->add($territoire);
        }

        return $this;
    }

    public function removeTerritoire(Territoire $territoire): self
    {
        $this->territoires->removeElement($territoire);

        return $this;
    }

    public function getTerritoireIds(): array
    {
        $result = [];
        $territoires = $this->getTerritoires();
        foreach ($territoires as $territoire) {
            $result[] = $territoire->getId();
        }

        return $result;
    }

    /**
     * @return Collection<int, Signalement>
     */
    public function getSignalements(): Collection
    {
        return $this->signalements;
    }

    public function addSignalement(Signalement $signalement): self
    {
        if (!$this->signalements->contains($signalement)) {
            $this->signalements->add($signalement);
            $signalement->setEntreprise($this);
        }

        return $this;
    }

    public function removeSignalement(Signalement $signalement): self
    {
        if ($this->signalements->removeElement($signalement)) {
            // set the owning side to null (unless already changed)
            if ($signalement->getEntreprise() === $this) {
                $signalement->setEntreprise(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Employe>
     */
    public function getEmployes(): Collection
    {
        return $this->employes;
    }

    public function addEmploye(Employe $employe): self
    {
        if (!$this->employes->contains($employe)) {
            $this->employes->add($employe);
            $employe->setEntreprise($this);
        }

        return $this;
    }

    public function removeEmploye(Employe $employe): self
    {
        if ($this->employes->removeElement($employe)) {
            // set the owning side to null (unless already changed)
            if ($employe->getEntreprise() === $this) {
                $employe->setEntreprise(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Intervention>
     */
    public function getInterventions(): Collection
    {
        return $this->interventions;
    }

    public function addInterventions(Intervention $intervention): self
    {
        if (!$this->interventions->contains($intervention)) {
            $this->interventions->add($intervention);
            $intervention->setEntreprise($this);
        }

        return $this;
    }

    public function removeInterventions(Intervention $intervention): self
    {
        if ($this->interventions->removeElement($intervention)) {
            // set the owning side to null (unless already changed)
            if ($intervention->getEntreprise() === $this) {
                $intervention->setEntreprise(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, MessageThread>
     */
    public function getMessagesThread(): Collection
    {
        return $this->messagesThread;
    }

    public function addMessagesThread(MessageThread $messagesThread): self
    {
        if (!$this->messagesThread->contains($messagesThread)) {
            $this->messagesThread->add($messagesThread);
            $messagesThread->setEntreprise($this);
        }

        return $this;
    }

    public function removeMessagesThread(MessageThread $messagesThread): self
    {
        if ($this->messagesThread->removeElement($messagesThread)) {
            // set the owning side to null (unless already changed)
            if ($messagesThread->getEntreprise() === $this) {
                $messagesThread->setEntreprise(null);
            }
        }

        return $this;
    }

    public function isActive(): bool
    {
        return $this->user && Status::ACTIVE === $this->user->getStatus();
    }
}

templates/front_suivi_usager/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Suivi de mon signalement{% endblock %}

{% block body %}

{% if not signalement.closedAt %}
    {% include "front_suivi_usager/modal-empty-estimations.html.twig" %}
    {% for intervention in interventions_to_answer %}
        {% include "front_suivi_usager/modal-choice-estimation.html.twig" %}
    {% endfor %}
    {% if intervention_accepted_by_usager %}
        {% include "front_suivi_usager/modal-estimation-accepted.html.twig" %}
    {% endif %}

    {% if signalement.autotraitement and signalement.reminderAutotraitementAt %}
        {% include "front_suivi_usager/modal-probleme-resolu.html.twig" %}
    {% endif %}
    {% if not signalement.autotraitement and intervention_accepted_by_usager and intervention_accepted_by_usager.reminderResolvedByEntrepriseAt %}
        {% include "front_suivi_usager/modal-probleme-resolu-pro.html.twig" %}
    {% endif %}

    {% include "front_suivi_usager/modal-toujours-punaises.html.twig" %}
    {% include "front_suivi_usager/modal-toujours-punaises-pro.html.twig" %}
    {% include "front_suivi_usager/modal-close-signalement.html.twig" %}
{% endif %}

<div class="suivi-usager fr-container fr-my-3v">

    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div role="status" class="fr-alert fr-alert--{{ label }} fr-alert--sm fr-mb-3v">
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    {% endfor %}

    <div class="fr-grid-row fr-grid-row--gutters">
        <div class="fr-col fr-col-12 fr-col-lg-6">
            <h1 class="fr-h2">Suivi de votre signalement #{{ signalement.reference }}</h1>
            <h2 class="fr-h3">A propos de votre signalement</h2>

            {% include "common/components/progression-signalement.html.twig" %}

            {% if not signalement.autotraitement %}
            <div class="fr-alert fr-alert--warning fr-mb-5w">
                <p>
                    Pour un suivi sécurisé, nous vous recommandons de ne pas transmettre vos coordonnées en direct 
                    – la société sélectionnée vous contactera, une fois votre choix effectué.
                    N'oubliez pas de prévenir votre propriétaire / bailleur !
                </p>
            </div>
            {% endif %}

            {% if not signalement.resolvedAt and not signalement.closedAt %}
            <div class="fr-grid-row fr-grid-row--gutters align-center">
                <div class="fr-col fr-col-12 fr-col-lg-6 fr-mb-3v">
                    <a class="fr-link fr-link--download" download href="{{ link_pdf }}">
                        Télécharger le protocole <span class="fr-link__detail">PDF – {{size_pdf|format_bytes}}</span>
                    </a>
                </div>

                <div class="fr-col fr-col-12 fr-col-lg-6 fr-mb-3v">
                    {% if signalement.autotraitement and signalement.territoire.active and not signalement.logementSocial %}
                        <form action="{{ path('app_signalement_switch_pro', {'uuid': signalement.uuid }) }}" method="POST" class="fr-mb-3v">
                            <input type="hidden" name="_csrf_token" value="{{ csrf_token('signalement_switch_pro') }}">
                            <button class="fr-btn fr-btn--icon-left fr-icon-check-line color-check">Trouver une entreprise labellisée</button>
                        </form>

                    {% else %}
                        <a href="#" class="fr-btn fr-btn--icon-left fr-icon-close-line color-close" data-fr-opened="false" aria-controls="fr-modal-close-signalement">Arrêter la procédure</a>
                    {% endif %}
                </div>
            </div>
            {% endif %}

            <section class="fr-accordion fr-mt-5w">
                <h3 class="fr-accordion__title">
                    <button class="fr-accordion__btn" aria-expanded="false" aria-controls="accordion-info-signalement">Info du signalement</button>
                </h3>
                <div class="fr-collapse" id="accordion-info-signalement">
                    Référence : #{{ signalement.reference }}
                    <br>
                    Date de dépot : {{ signalement.createdAt.format('d/m/Y') }}
                    <br>
                    Infestation estimée : {{ niveau_infestation }}
                    <br>
                    Protocole choisi : {{ signalement.autotraitement ? 'auto traitement' : 'intervention professionnelle' }}
                </div>
            </section>
        </div>

        <aside class="fr-col fr-col-12 fr-col-lg-6">
            {% include "common/components/signalement-detail-evenements.html.twig" %}
        </aside>
    </div>
</div>
{% endblock %}

templates/front_suivi_usager/messages_thread.html.twig
{% extends 'base.html.twig' %}

{% block title %}Suivi de mon signalement - Messages {% endblock %}
{% block body %}

    <div class="suivi-usager fr-container fr-my-3v">
        <a class="fr-link fr-fi-arrow-left-line fr-link--icon-left"
           href="{{
           app.user
           ? path('app_signalement_view', {'uuid': signalement.uuid})
           : path('app_suivi_usager_view', {'uuidPublic': signalement.uuidPublic})
           }}">Retour</a>
        <h2 class="fr-my-3v"> {{ is_granted('ROLE_ADMIN') ? 'Les échanges' : 'Vos échanges'  }} avec {{ entreprise_name }}</h2>
        <section>
            {% include 'common/components/messages-thread.html.twig' with
                {
                    'haveScrollbar' : false,
                    'sender': signalement.emailOccupant,
                    'recipient': entreprise_name
                }
            %}

            {% if not is_granted('ROLE_ADMIN') %}
                {% if entreprise.isActive %}
                    <form action="{{ path('app_public_thread_message_send',{
                        'uuid': messages_thread_uuid,
                    }) }}" id="form-send-message" name="send_message" method="POST">
                        <div class="fr-input-group fr-col-12">
                            <label for="message">Votre message <span class="fr-hint-text help-text">10 caractères minimum</span></label>
                            <textarea class="fr-input edit-zone" name="message" id="message" cols="10" rows="3" required minlength="10" aria-describedby="message-confirmation"></textarea>
                            <input type="hidden" name="_token" value="{{ csrf_token('send_message') }}">
                        </div>
                        <div class="fr-col-12 fr-text--center">
                            <button type="submit" class="fr-btn fr-rounded fr-btn--icon-left fr-icon-send-plane-fill"> Envoyer le
                                message
                            </button>
                        </div>
                        <div id="message-confirmation" class="message-confirmation fr-mt-1w fr-alert fr-hidden">
                            <h3 class="fr-alert__title fr-text--md"></h3>
                        </div>
                    </form>
                {% else %}
                    <div class="fr-notice fr-notice--warning">
                        <div class="fr-container">
                            <div class="fr-notice__body">
                                <p>
                                    <span class="fr-notice__title">Cette entreprise n'est plus active sur la plateforme</span>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        </section>
    </div>

{% endblock %}

templates/front_suivi_usager/modal-choice-estimation.html.twig
<dialog aria-labelledby="fr-modal-title-modal-choice-estimation-{{ intervention.id }}" id="fr-modal-choice-estimation-{{ intervention.id }}" class="fr-modal fr-sidemodal">
    <div class="fr-container fr-container--fluid fr-container-md">
        <div class="fr-grid-row fr-grid-row--center">
            <div class="fr-col-12 fr-col-md-8 fr-col-lg-6">
                <div class="fr-modal__body">
                    <div class="fr-modal__header">
                        <button class="fr-link--close fr-link" title="Fermer la fenêtre modale" aria-controls="fr-modal-choice-estimation-{{ intervention.id }}" type="button">Fermer</button>
                    </div>
                    <div class="fr-modal__content">
                        <h1 id="fr-modal-title-modal-choice-estimation-{{ intervention.id }}" class="fr-modal__title">Estimation {{ intervention.entreprise.nom }}</h1>
                        
                        <div class="fr-notice fr-notice--info">
                            <div class="fr-container">
                                <div class="fr-notice__body">
                                    <p class="fr-notice__title">
                                    Le prix peut varier après une visite de votre domicile par l'entreprise.
                                    </p>
                                </div>
                            </div>
                        </div>

                        <p class="fr-mt-5v">
                            <strong>Commentaire :</strong>
                            {{ intervention.commentaireEstimation }}
                        </p>

                        <p>
                            <strong>Montant :</strong>
                            {{ intervention.montantEstimation }}&nbsp;€
                        </p>
                        
                        {% if intervention.entreprise and intervention.entreprise.isActive %}
                            <p>
                                <u>Si vous acceptez</u> cette estimation, les estimations des autres entreprises seront automatiquement refusées.
                            </p>

                            <p>
                                <u>Si vous refusez</u> cette estimation, vous ne pourrez pas revenir en arrière.
                            </p>

                            {% if is_last_intervention_to_answer %}
                            <div class="fr-alert fr-alert--warning">
                                <h3 class="fr-alert__title">Dernière estimation</h3>
                                <p>Si vous refusez cette estimation, vous pourrez être réorienté vers l'auto-traitement ou l'arrêt de la procédure.</p>
                            </div>
                            {% endif %}

                            <form action="{{ path('app_signalement_estimation_choice', {'uuid': intervention.signalement.uuid, 'id': intervention.id }) }}" method="POST" class="align-center fr-mt-3v">
                                <input type="hidden" name="_csrf_token" value="{{ csrf_token('signalement_estimation_choice') }}">
                                <button type="submit" class="fr-btn fr-btn--sm fr-btn--icon-left fr-icon-check-line color-check fr-mb-3v" name="action" value="accept">Accepter</button>
                                <button type="submit" class="fr-btn fr-btn--sm fr-btn--icon-left fr-icon-close-line color-close" name="action" value="refuse">Refuser</button>
                            </form>
                        {% else %}
                            <div class="fr-notice fr-notice--warning">
                                <div class="fr-container">
                                    <div class="fr-notice__body">
                                        <p>
                                            <span class="fr-notice__title">Cette entreprise n'est plus active sur la plateforme</span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <form action="{{ path('app_signalement_estimation_choice', {'uuid': intervention.signalement.uuid, 'id': intervention.id }) }}" method="POST" class="align-center fr-mt-3v">
                                <input type="hidden" name="_csrf_token" value="{{ csrf_token('signalement_estimation_choice') }}">
                                <button type="submit" class="fr-btn fr-btn--sm fr-btn--icon-left fr-icon-close-line color-close" name="action" value="refuse">Refuser</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</dialog>

templates/front_suivi_usager/modal-close-signalement.html.twig
<dialog aria-labelledby="fr-modal-title-modal-close-signalement" id="fr-modal-close-signalement" class="fr-modal">
    <div class="fr-container fr-container--fluid fr-container-md">
        <div class="fr-grid-row fr-grid-row--center">
            <div class="fr-col-12 fr-col-md-8 fr-col-lg-6">
                <div class="fr-modal__body">
                    <div class="fr-modal__header">
                        <button class="fr-link--close fr-link" title="Fermer la fenêtre modale" aria-controls="fr-modal-close-signalement" type="button">Fermer</button>
                    </div>
                    <div class="fr-modal__content">
                        <h1 id="fr-modal-title-modal-close-signalement" class="fr-modal__title">Arrêter la procédure</h1>
                        <p>
                            En arrêtant la procédure :<br>
                            <ul>
                                <li>Votre signalement sera clôturé</li>
                                <li>Les estimations acceptées ou en attente seront refusées</li>
                                <li>Vous ne pourrez plus répondre aux entreprises</li>
                                <li>Les entreprises ne pourront plus vous contacter</li>
                            </ul>
                            Voulez-vous vraiment arrêter la procédure ?
                        </p>
                        <div>
                            <form action="{{ path('app_signalement_stop', {'uuid': signalement.uuid }) }}" method="POST" class="fr-mb-3v">
                                <input type="hidden" name="_csrf_token" value="{{ csrf_token('signalement_stop') }}">
                                <button class="fr-btn fr-btn--icon-left fr-icon-close-line">Oui, arrêter la procédure</button>
                            </form>
                        </div>
                        <p class="align-center fr-mt-3v">
                            <button class="fr-btn  fr-btn--tertiary fr-btn--icon-left  fr-icon-arrow-go-back-line" aria-controls="fr-modal-close-signalement" href="#">Retour</button>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</dialog>

templates/front_suivi_usager/modal-empty-estimations.html.twig
<dialog aria-labelledby="fr-modal-title-modal-empty-estimations" id="fr-modal-empty-estimations" class="fr-modal fr-sidemodal">
    <div class="fr-container fr-container--fluid fr-container-md">
        <div class="fr-grid-row fr-grid-row--center">
            <div class="fr-col-12 fr-col-md-8 fr-col-lg-6">
                <div class="fr-modal__body">
                    <div class="fr-modal__header">
                        <button class="fr-link--close fr-link" title="Fermer la fenêtre modale" aria-controls="fr-modal-empty-estimations" type="button">Fermer</button>
                    </div>
                    <div class="fr-modal__content">
                        {% if accepted_interventions|length > 0 %}
                            <h1 id="fr-modal-title-modal-empty-estimations" class="fr-modal__title">Plus d'estimation disponible</h1>
                            <p>
                                Vous avez refusé toutes les estimations de nos entreprises disponibles.
                                Votre problème ne peut donc pas être pris en charge.
                                <br>
                                Vous pouvez arrêter la procédure ou opter pour le traitement à domicile, à réaliser vous-même.
                            </p>
                        {% else %}
                            <h1 id="fr-modal-title-modal-empty-estimations" class="fr-modal__title">Aucune entreprise disponible</h1>
                            <p>
                                Malheureusement, aucune entreprise n'est actuellement disponible pour prendre en charge votre problème.
                                <br>
                                Vous pouvez arrêter la procédure ou opter pour le traitement à domicile, à réaliser vous-même.
                            </p>
                        {% endif %}
                        <p>
                            Que souhaitez-vous faire ?
                        </p>
                        <div>
                            <form action="{{ path('app_signalement_switch_autotraitement', {'uuid': signalement.uuid }) }}" method="POST" class="fr-mb-3v">
                                <input type="hidden" name="_csrf_token" value="{{ csrf_token('signalement_switch_autotraitement') }}">
                                <button class="fr-btn fr-btn--sm fr-btn--icon-left fr-icon-check-line color-check">Essayer l'auto-traitement</button>
                            </form>

                            <form action="{{ path('app_signalement_stop', {'uuid': signalement.uuid }) }}" method="POST" class="fr-mb-3v">
                                <input type="hidden" name="_csrf_token" value="{{ csrf_token('signalement_stop') }}">
                                <button class="fr-btn fr-btn--sm fr-btn--icon-left fr-icon-close-line color-close">Arrêter la procédure</button>
                            </form>
                        </div>
                        <p class="align-center fr-mt-3v">
                            <button class="fr-btn  fr-btn--tertiary fr-btn--icon-left  fr-icon-arrow-go-back-line" aria-controls="fr-modal-empty-estimations" href="#">Retour</button>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</dialog>

templates/front_suivi_usager/modal-estimation-accepted.html.twig
<dialog aria-labelledby="fr-modal-title-modal-estimation-accepted-{{ intervention_accepted_by_usager.id }}" id="fr-modal-estimation-accepted-{{ intervention_accepted_by_usager.id }}" class="fr-modal fr-sidemodal">
    <div class="fr-container fr-container--fluid fr-container-md">
        <div class="fr-grid-row fr-grid-row--center">
            <div class="fr-col-12 fr-col-md-8 fr-col-lg-6">
                <div class="fr-modal__body">
                    <div class="fr-modal__header">
                        <button class="fr-link--close fr-link" title="Fermer la fenêtre modale" aria-controls="fr-modal-estimation-accepted-{{ intervention_accepted_by_usager.id }}" type="button">Fermer</button>
                    </div>
                    <div class="fr-modal__content">
                        <h1 id="fr-modal-title-modal-estimation-accepted-{{ intervention_accepted_by_usager.id }}" class="fr-modal__title">Estimation {{ intervention_accepted_by_usager.entreprise.nom }}</h1>
                        
                        <div class="fr-notice fr-notice--info">
                            <div class="fr-container">
                                <div class="fr-notice__body">
                                    <p class="fr-notice__title">
                                        Vous avez accepté l'estimation le {{ intervention_accepted_by_usager.choiceByUsagerAt.format('d/m/Y') }}.
                                    </p>
                                </div>
                            </div>
                        </div>

                        <p class="fr-mt-5v">
                            <strong>Commentaire :</strong>
                            {{ intervention_accepted_by_usager.commentaireEstimation }}
                        </p>

                        <p>
                            <strong>Montant :</strong>
                            {{ intervention_accepted_by_usager.montantEstimation }}&nbsp;€
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</dialog>

templates/front_suivi_usager/modal-toujours-punaises.html.twig
<dialog aria-labelledby="fr-modal-title-modal-toujours-punaises" id="fr-modal-toujours-punaises" class="fr-modal">
    <div class="fr-container fr-container--fluid fr-container-md">
        <div class="fr-grid-row fr-grid-row--center">
            <div class="fr-col-12 fr-col-md-8 fr-col-lg-6">
                <div class="fr-modal__body">
                    <div class="fr-modal__header">
                        <button class="fr-link--close fr-link" title="Fermer la fenêtre modale" aria-controls="fr-modal-toujours-punaises" type="button">Fermer</button>
                    </div>
                    <div class="fr-modal__content">
                        <h1 id="fr-modal-title-modal-toujours-punaises" class="fr-modal__title">Vous avez toujours un problème de punaises</h1>
                        <p>
                            Vous avez indiqué avoir toujours un problème de punaises de lit.
                            {% if signalement.territoire.active %}
                            <br>
                            Nous pouvons vous aider à trouver une entreprise labellisée pour traiter votre logement.
                            {% endif %}
                        </p>
                        <p>
                            Que souhaitez-vous faire ?
                        </p>
                        <div>
                            {% if signalement.territoire.active %}
                            <form action="{{ path('app_signalement_switch_pro', {'uuid': signalement.uuid }) }}" method="POST" class="fr-mb-3v">
                                <input type="hidden" name="_csrf_token" value="{{ csrf_token('signalement_switch_pro') }}">
                                <button class="fr-btn fr-btn--sm fr-btn--icon-left fr-icon-check-line color-check">Trouver une entreprise</button>
                            </form>
                            {% endif %}

                            <form action="{{ path('app_signalement_stop', {'uuid': signalement.uuid }) }}" method="POST" class="fr-mb-3v">
                                <input type="hidden" name="_csrf_token" value="{{ csrf_token('signalement_stop') }}">
                                <button class="fr-btn fr-btn--sm fr-btn--icon-left fr-icon-close-line color-close">Arrêter la procédure</button>
                            </form>
                        </div>
                        <p class="align-center fr-mt-3v">
                            <button class="fr-btn  fr-btn--tertiary fr-btn--icon-left  fr-icon-arrow-go-back-line" aria-controls="fr-modal-toujours-punaises" href="#">Retour</button>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</dialog>